site_name: PlantDB
site_description: PlantDB documentation.
site_author: ROMI Team
site_url: https://romi.github.io/plantdb/
copyright: 'CC Attribution-NonCommercial-ShareAlike 4.0 International'
repo_url: https://github.com/romi/plantdb

nav:
  - 'Home': index.md
  - 'REST API': rest_api.md
  - 'Reference API': reference/


theme:
  name: 'material'
  font:
    text: Nunito Sans
    code: Ubuntu Mono
  logo: 'assets/images/ROMI_logo_white.svg'
  favicon: 'assets/images/ROMI_ICON_green.png'
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy


extra:
  homepage: https://romi.github.io/plantdb/
  social:
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/ROMI_EU_PROJECT'
    - icon: fontawesome/brands/facebook
      link: 'https://www.facebook.com/ROMIEUProject'
    - icon: fontawesome/brands/github
      link: 'https://github.com/romi/plantdb'
  project: 'The ROMI project has received funding from the European Community’s H2020 Programme under Grant Agreement No. 773875.'
  footer_logo: '/assets/images/eu-flag.png'
  repo_name: plantdb
  repo_url: https://github.com/romi/plantdb


markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - toc:
      permalink: Link
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          validator: !!python/name:markdown_exec.validator
          format: !!python/name:markdown_exec.formatter
  - pymdownx.tabbed:
      alternate_style: true


plugins:
  - search
  - markdown-exec
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            docstring_style: numpy
            docstring_section_style: table
            ignore_init_summary: true
            merge_init_into_class: true
            show_docstring_examples: true
            show_docstring_raises: true
            signature_crossrefs: true


extra_css:
  - assets/css/extra.css


extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://buttons.github.io/buttons.js'
