# This workflow will build the Docker image and publish it to Docker Hub in the 'roboticsmicrofarms' repo.

# This action is inspired from official GitHub doc:
#  https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
# Metadata configuration here:
#  https://github.com/docker/metadata-action
# Build & push job configuration here:
#  https://github.com/docker/build-push-action
# https://github.com/docker/login-action

name: Docker image

on:
  # Automatic trigger on release
  release:
    types: [ published ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: docker/Dockerfile
          tags: roboticsmicrofarms/plantdb:${{ github.sha }}

  test_docker:
    name: Test built docker image.
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
      - name: Test
        run: |
          docker run --rm roboticsmicrofarms/plantdb:{{ github.sha }} \
            -c "export ROMI_DB='/myapp/db' && mkdir -p $ROMI_DB && shared_fsdb $ROMI_DB -d all"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: docker/Dockerfile
          tags: roboticsmicrofarms/plantdb:latest
