# This workflow will build the Docker image and publish it to Docker Hub in the 'roboticsmicrofarms' repo.

# Github context:
#   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
# This action is inspired from official GitHub doc:
#  https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub
# -- Metadata configuration here:
#  https://github.com/marketplace/actions/docker-metadata-action
# -- Build & push job configuration here:
#  https://github.com/marketplace/actions/build-and-push-docker-images

name: Docker image

on:
  # Automatic trigger on release
  release:
    types: [ published ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: docker-hub
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: roboticsmicrofarms/plantdb
          tags: type=sha,format=short,prefix=
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
      - name: Cache docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=/tmp/myimage.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: myimage
          path: /tmp/myimage.tar

  test_docker:
    name: Test built docker image.
    runs-on: ubuntu-latest
    needs: docker
    environment: docker-hub
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a
      - name: Test image
        run: |
          docker run --rm ${{ steps.meta.outputs.tags }} \
            /bin/bash -c "export ROMI_DB='/myapp/db' && mkdir -p $ROMI_DB && shared_fsdb $ROMI_DB -d all"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push as latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: docker/Dockerfile
          tags: roboticsmicrofarms/plantdb:latest
