# pull_request.yml
name: CI UnitTests

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # Build the Docker image, targeting the test stage
      - name: Build Docker image
        run: |
          docker container prune -f
          docker build --target test -t plantdb-test:${{ github.sha }} .

      # Clean up
      - name: Remove Docker image
        if: always()
        run: |
          docker image rm plantdb-test:${{ github.sha }} --force