# pull_request.yml
name: CI UnitTests

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      # 1 Checkout the repo (including submodules if you need them)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      # 2 Build the Docker image
      - name: Build Docker image
        run: |
          docker container prune -f
          ./docker/build.sh -t ${{ github.sha }} --no-cache

      # 3 Run the unit tests inside the image
      - name: Run unit tests
        run: |
          ./docker/run.sh -t ${{ github.sha }} --unittest

      # 4 Clean up
      - name: Remove Docker image
        if: always()
        run: |
          docker container prune -f
          docker image rm roboticsmicrofarms/plantdb:${{ github.sha }} --force